# Generated by Django 4.0.1 on 2022-02-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], max_length=5, verbose_name='Calendar year')),
                ('semester_time', models.CharField(choices=[('SPR', 'Spring'), ('SUM', 'Summer'), ('FAL', 'Fall'), ('WNT', 'Winter')], max_length=3, verbose_name='Time held')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='N/A', max_length=50, verbose_name='Class name')),
                ('course_id', models.CharField(blank=True, max_length=10, verbose_name='Course ID')),
                ('catalog_id', models.CharField(blank=True, max_length=10, verbose_name='Catalog ID')),
                ('section', models.CharField(blank=True, max_length=10, verbose_name='Section')),
                ('day', models.CharField(max_length=10, verbose_name='Day')),
                ('facility_id', models.CharField(blank=True, max_length=20, verbose_name='Facility ID')),
                ('facility_building', models.CharField(blank=True, max_length=50, verbose_name='Facility Building')),
                ('instructor', models.CharField(blank=True, max_length=50, verbose_name='Instructor')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('staffed', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborganizer.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
            },
        ),
    ]
