# Generated by Django 4.0.1 on 2022-02-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_id', models.CharField(blank=True, max_length=10)),
                ('catalog_number', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('facility_id', models.CharField(blank=True, max_length=20)),
                ('facility_bulding', models.CharField(blank=True, max_length=50)),
                ('instructor', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, verbose_name='Calendar year')),
                ('semester_time', models.CharField(choices=[('SPR', 'Spring'), ('SUM', 'Summer'), ('FAL', 'Fall'), ('WNT', 'Winter')], max_length=3, verbose_name='Time held')),
                ('labs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborganizer.lab')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
    ]
