# Generated by Django 4.0.1 on 2022-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0002_remove_ta_assignments'),
        ('laborganizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='assigned_tas',
            field=models.ManyToManyField(blank=True, to='teachingassistant.TA'),
        ),
    ]
