# Generated by Django 4.0.1 on 2022-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='staffed',
            field=models.BooleanField(default=False),
        ),
    ]
