# Generated by Django 4.0.1 on 2022-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0002_alter_semester_labs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='facility_bulding',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='name',
        ),
        migrations.AddField(
            model_name='lab',
            name='class_name',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Class name'),
        ),
        migrations.AddField(
            model_name='lab',
            name='facility_building',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facility Building'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Catalog Number'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='course_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='day',
            field=models.CharField(max_length=10, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='facility_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Facility ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='instructor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='time',
            field=models.CharField(max_length=50, verbose_name='Time'),
        ),
    ]
