# Generated by Django 4.0.1 on 2022-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0003_remove_lab_facility_bulding_remove_lab_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='catalog_number',
        ),
        migrations.AddField(
            model_name='lab',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Catalog ID'),
        ),
    ]
