# Generated by Django 4.0.1 on 2022-02-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0003_remove_lab_assigned_tas_lab_assigned_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='time',
        ),
        migrations.AddField(
            model_name='lab',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='lab',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='lab',
            name='subject',
            field=models.CharField(default='nothing', max_length=10, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='catalog_id',
            field=models.CharField(max_length=10, verbose_name='Catalog ID'),
        ),
    ]
