# Generated by Django 4.0.1 on 2022-02-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0004_remove_lab_catalog_number_lab_catalog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='labs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laborganizer.lab', verbose_name='Labs'),
        ),
    ]
