# Generated by Django 4.0.1 on 2022-02-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0005_remove_lab_day_lab_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='assigned_ta',
        ),
    ]
