# Generated by Django 4.0.1 on 2022-02-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0006_remove_lab_assigned_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
