# Generated by Django 4.0.1 on 2022-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0007_alter_lab_end_time_alter_lab_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='course_id',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Course ID'),
        ),
    ]
