# Generated by Django 4.0.1 on 2022-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0008_alter_lab_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowTAEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
