# Generated by Django 4.0.1 on 2022-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0011_alter_semester_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowtaedit',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowtaedit',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
