# Generated by Django 4.0.2 on 2022-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0026_scorepair_schedule_key'),
        ('laborganizer', '0015_alter_allowtaedit_date_alter_allowtaedit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_1', models.ManyToManyField(blank=True, related_name='lab_1', to='laborganizer.Lab')),
                ('lab_2', models.ManyToManyField(blank=True, related_name='lab_2', to='laborganizer.Lab')),
                ('ta_1', models.ManyToManyField(blank=True, related_name='ta_1', to='teachingassistant.TA')),
                ('ta_2', models.ManyToManyField(blank=True, related_name='ta_2', to='teachingassistant.TA')),
            ],
        ),
    ]
