# Generated by Django 4.0.1 on 2022-03-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0016_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
