# Generated by Django 4.0.1 on 2022-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0017_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_time',
            field=models.CharField(choices=[('SPR', 'Spring'), ('SUM', 'Summer'), ('FAL', 'Fall'), ('WNT', 'Winter')], max_length=3, null=True, verbose_name='Time held'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], null=True, verbose_name='Calendar year'),
        ),
    ]
