# Generated by Django 4.0.1 on 2022-04-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0019_alter_semester_semester_time_alter_semester_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='staffed',
        ),
    ]
