# Generated by Django 4.0.1 on 2022-04-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0020_remove_lab_staffed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='days',
            field=models.CharField(help_text='Characters separated by spaces', max_length=10, verbose_name='Days'),
        ),
    ]
