# Generated by Django 4.0.1 on 2022-04-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0013_history_is_assignment'),
        ('laborganizer', '0021_alter_lab_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('semester_time', models.CharField(blank=True, max_length=3)),
                ('template_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimization.templateschedule')),
            ],
        ),
    ]
