# Generated by Django 4.0.1 on 2022-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0022_locache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locache',
            name='semester_time',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='locache',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
