# Generated by Django 4.0.1 on 2022-02-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laborganizer', '0006_remove_lab_assigned_ta'),
        ('teachingassistant', '0017_ta_assigned_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ManyToManyField(to='laborganizer.Lab')),
                ('ta', models.ManyToManyField(to='teachingassistant.TA')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, verbose_name='Schedule Version')),
                ('assignments', models.ManyToManyField(to='optimization.TemplateAssignments')),
                ('semester', models.ManyToManyField(to='laborganizer.Semester')),
            ],
        ),
    ]
