# Generated by Django 4.0.1 on 2022-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0008_alter_lab_course_id'),
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateassignments',
            name='semester',
            field=models.ManyToManyField(to='laborganizer.Semester'),
        ),
    ]
