# Generated by Django 4.0.1 on 2022-03-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0010_alter_allowtaedit_options_allowtaedit_date_and_more'),
        ('optimization', '0003_rename_templateassignments_templateassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschedule',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='optimization.TemplateAssignment'),
        ),
        migrations.RemoveField(
            model_name='templateschedule',
            name='semester',
        ),
        migrations.AddField(
            model_name='templateschedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborganizer.semester'),
        ),
    ]
