# Generated by Django 4.0.1 on 2022-03-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0004_alter_templateschedule_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschedule',
            name='version_number',
            field=models.IntegerField(default=0, verbose_name='Schedule Version'),
        ),
    ]
