# Generated by Django 4.0.1 on 2022-03-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0005_alter_templateschedule_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateassignment',
            name='semester',
        ),
    ]
