# Generated by Django 4.0.1 on 2022-03-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0023_alter_classtime_options_classtime_days'),
        ('laborganizer', '0010_alter_allowtaedit_options_allowtaedit_date_and_more'),
        ('optimization', '0006_remove_templateassignment_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateassignment',
            name='lab',
        ),
        migrations.AddField(
            model_name='templateassignment',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborganizer.lab'),
        ),
        migrations.RemoveField(
            model_name='templateassignment',
            name='ta',
        ),
        migrations.AddField(
            model_name='templateassignment',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.ta'),
        ),
    ]
