# Generated by Django 4.0.1 on 2022-03-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0017_delete_history'),
        ('teachingassistant', '0026_scorepair_schedule_key'),
        ('optimization', '0008_templateassignment_schedule_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_node_id', models.IntegerField()),
                ('lab_1', models.ManyToManyField(blank=True, related_name='lab_1', to='laborganizer.Lab')),
                ('lab_2', models.ManyToManyField(blank=True, related_name='lab_2', to='laborganizer.Lab')),
                ('ta_1', models.ManyToManyField(blank=True, related_name='ta_1', to='teachingassistant.TA')),
                ('ta_2', models.ManyToManyField(blank=True, related_name='ta_2', to='teachingassistant.TA')),
                ('temp_sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_nodes', to='optimization.templateschedule')),
            ],
        ),
    ]
