# Generated by Django 4.0.1 on 2022-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0009_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='relative_node_id',
            field=models.IntegerField(blank=True),
        ),
    ]
