# Generated by Django 4.0.1 on 2022-03-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0011_alter_history_relative_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='temp_sched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='his_nodes', to='optimization.templateschedule'),
        ),
    ]
