# Generated by Django 4.0.1 on 2022-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0012_alter_history_temp_sched'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
