# Generated by Django 4.0.1 on 2022-02-05 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laborganizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField()),
                ('monday_end', models.TimeField()),
                ('tuesday_start', models.TimeField()),
                ('tuesday_end', models.TimeField()),
                ('wednesday_start', models.TimeField()),
                ('wednesday_end', models.TimeField()),
                ('thursday_start', models.TimeField()),
                ('thursday_end', models.TimeField()),
                ('friday_start', models.TimeField()),
                ('friday_end', models.TimeField()),
                ('saturday_start', models.TimeField()),
                ('saturday_end', models.TimeField()),
                ('sunday_start', models.TimeField()),
                ('sunday_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="TA's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="TA's last name")),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name="TA's student ID")),
                ('email', models.EmailField(max_length=250, verbose_name="TA's email")),
                ('contracted', models.BooleanField(blank=True, verbose_name='Contracted')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name="TA's experience")),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, verbose_name="TA's current year")),
                ('assignments', models.ManyToManyField(blank=True, to='laborganizer.Lab')),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.availability')),
                ('user_model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TA',
                'verbose_name_plural': "TA's",
            },
        ),
    ]
