# Generated by Django 4.0.1 on 2022-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laborganizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="TA's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="TA's last name")),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name="TA's student ID")),
                ('email', models.EmailField(max_length=250, verbose_name="TA's email")),
                ('availability', models.CharField(blank=True, max_length=100, verbose_name="TA's availability")),
                ('contracted', models.BooleanField(verbose_name='Contracted')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name="TA's experience")),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, verbose_name="TA's current year")),
                ('assignments', models.ManyToManyField(to='laborganizer.Lab')),
            ],
            options={
                'verbose_name': 'TA',
                'verbose_name_plural': "TA's",
            },
        ),
    ]
