# Generated by Django 4.0.1 on 2022-02-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laborganizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="TA's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="TA's last name")),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name="TA's student ID")),
                ('contracted', models.BooleanField(blank=True, verbose_name='Contracted')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name="TA's experience")),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, verbose_name="TA's current year")),
                ('assignments', models.ManyToManyField(blank=True, to='laborganizer.Lab')),
            ],
            options={
                'verbose_name': 'TA',
                'verbose_name_plural': "TA's",
            },
        ),
        migrations.CreateModel(
            name='Holds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_profile', models.BooleanField(default=True, verbose_name='Incomplete profile')),
                ('update_availability', models.BooleanField(default=False, verbose_name='Update availability!')),
                ('update_experience', models.BooleanField(default=False, verbose_name='Update experience!')),
                ('no_holds', models.BooleanField(default=False, verbose_name='No holds')),
                ('ta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.ta')),
            ],
            options={
                'verbose_name': 'Holds',
                'verbose_name_plural': 'Holds',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField()),
                ('monday_end', models.TimeField()),
                ('tuesday_start', models.TimeField()),
                ('tuesday_end', models.TimeField()),
                ('wednesday_start', models.TimeField()),
                ('wednesday_end', models.TimeField()),
                ('thursday_start', models.TimeField()),
                ('thursday_end', models.TimeField()),
                ('friday_start', models.TimeField()),
                ('friday_end', models.TimeField()),
                ('saturday_start', models.TimeField()),
                ('saturday_end', models.TimeField()),
                ('sunday_start', models.TimeField()),
                ('sunday_end', models.TimeField()),
                ('ta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.ta')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': "Availability's",
            },
        ),
    ]
