# Generated by Django 4.0.1 on 2022-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0001_initial'),
        ('teachingassistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='laborganizer.Lab'),
        ),
    ]
