# Generated by Django 4.0.1 on 2022-02-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta',
            name='assignments',
        ),
    ]
