# Generated by Django 4.0.1 on 2022-02-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0002_remove_ta_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='first_name',
            field=models.CharField(default='missing', max_length=50, verbose_name="TA's first name"),
        ),
        migrations.AlterField(
            model_name='ta',
            name='last_name',
            field=models.CharField(default='missing', max_length=50, verbose_name="TA's last name"),
        ),
        migrations.AlterField(
            model_name='ta',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name="TA's student ID"),
        ),
    ]
