# Generated by Django 4.0.1 on 2022-02-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0003_alter_ta_first_name_alter_ta_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='contracted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contracted'),
        ),
    ]
