# Generated by Django 4.0.1 on 2022-02-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0007_ta_availability_key_ta_holds_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holds',
            name='ta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.ta', verbose_name='TA'),
        ),
        migrations.AlterField(
            model_name='holds',
            name='update_availability',
            field=models.BooleanField(default=False, verbose_name='Update availability'),
        ),
        migrations.AlterField(
            model_name='holds',
            name='update_experience',
            field=models.BooleanField(default=False, verbose_name='Update experience'),
        ),
    ]
