# Generated by Django 4.0.1 on 2022-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0008_alter_holds_ta_alter_holds_update_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holds',
            name='no_holds',
        ),
    ]
