# Generated by Django 4.0.1 on 2022-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0009_remove_holds_no_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='scores',
            field=models.TextField(blank=True, null=True, verbose_name="TA's optimization scores"),
        ),
    ]
