# Generated by Django 4.0.1 on 2022-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0011_alter_ta_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='scores',
            field=models.TextField(blank=True, null=True, verbose_name="TA's optimization scores"),
        ),
    ]
