# Generated by Django 4.0.1 on 2022-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0012_alter_ta_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_catalog_id', models.CharField(max_length=10, verbose_name='Catalog ID for score')),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
        ),
        migrations.RemoveField(
            model_name='ta',
            name='scores',
        ),
        migrations.AddField(
            model_name='ta',
            name='scores',
            field=models.ManyToManyField(to='teachingassistant.ScorePair'),
        ),
    ]
