# Generated by Django 4.0.1 on 2022-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0005_remove_lab_day_lab_days'),
        ('teachingassistant', '0013_scorepair_remove_ta_scores_ta_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='assigned_semesters',
            field=models.ManyToManyField(blank=True, null=True, to='laborganizer.Semester'),
        ),
    ]
