# Generated by Django 4.0.1 on 2022-02-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0015_alter_ta_assigned_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='scores',
            field=models.ManyToManyField(blank=True, to='teachingassistant.ScorePair'),
        ),
    ]
