# Generated by Django 4.0.1 on 2022-02-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0006_remove_lab_assigned_ta'),
        ('teachingassistant', '0016_alter_ta_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='assigned_labs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laborganizer.lab'),
        ),
    ]
