# Generated by Django 4.0.1 on 2022-02-28 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0018_remove_ta_assigned_labs_ta_assigned_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachingassistant.ta')),
            ],
        ),
    ]
