# Generated by Django 4.0.1 on 2022-02-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0019_classtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='availability',
            name='class_times',
            field=models.ManyToManyField(to='teachingassistant.ClassTime'),
        ),
    ]
