# Generated by Django 4.0.1 on 2022-03-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0021_classtime_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='semester',
        ),
    ]
