# Generated by Django 4.0.1 on 2022-03-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laborganizer', '0011_alter_semester_year'),
        ('teachingassistant', '0023_alter_classtime_options_classtime_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepair',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laborganizer.semester'),
        ),
    ]
