# Generated by Django 4.0.1 on 2022-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0024_scorepair_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='experience',
            field=models.TextField(blank=True, verbose_name="TA's experience"),
        ),
    ]
