# Generated by Django 4.0.1 on 2022-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0025_alter_ta_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepair',
            name='schedule_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Schedule Key'),
        ),
    ]
