# Generated by Django 4.0.1 on 2022-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachingassistant', '0026_scorepair_schedule_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="TA's student ID"),
        ),
    ]
