# Generated by Django 4.0.1 on 2022-02-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_accounts', models.TextField(blank=True, null=True)),
                ('returning_accounts', models.TextField(blank=True, null=True)),
                ('old_email_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
