# Generated by Django 4.0.1 on 2022-02-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinformation',
            name='old_email_file_name',
        ),
    ]
